/**
 * Built-in background images.
 *
 * Files live in `public/backgrounds/<id>.jpg` (full size, ≤ 2560 px) and
 * `public/backgrounds/<id>-thumb.jpg` (tile preview). The current set is
 * generated by `scripts/generate-backgrounds.sh`; photos from a stock library
 * such as Unsplash (https://unsplash.com/license) carry `author` and
 * `sourceUrl`, which the picker shows as attribution.
 */
export type PhotoPreset = {
  id: string;
  /** Short description, used as the accessible name of the tile. */
  name: string;
  /** Photographer, for stock photos. */
  author?: string;
  /** Photo page on the stock library, for stock photos. */
  sourceUrl?: string;
};

export const PHOTO_PRESETS: PhotoPreset[] = [
  { id: "morning-haze", name: "Morning haze" },
  { id: "pastel-bokeh", name: "Pastel bokeh" },
  { id: "sky-leaves", name: "Sky through leaves" },
  { id: "white-fabric", name: "White fabric" },
  { id: "golden-hour", name: "Golden hour" },
  { id: "green-field", name: "Green field" },
  { id: "lavender-mist", name: "Lavender mist" },
  { id: "dark-streak", name: "Light streak" },
  { id: "night-bokeh", name: "Night bokeh" },
  { id: "aurora", name: "Aurora" },
];

export const photoSrc = (id: string) => `/backgrounds/${id}.jpg`;
export const photoThumbSrc = (id: string) => `/backgrounds/${id}-thumb.jpg`;

export function getPhotoPreset(id: string): PhotoPreset | undefined {
  return PHOTO_PRESETS.find((photo) => photo.id === id);
}
