/**
 * Built-in video backgrounds: original, seamless 8 s loops of soft colour
 * lights, generated by `scripts/generate-background-videos.mjs` into
 * `public/backgrounds/videos/<id>.webm` (VP9) and `<id>.mp4` (H.264), both
 * 1440 × 1440, with a `<id>-thumb.jpg` poster for the tiles.
 */
export type VideoPreset = {
  id: string;
  name: string;
  width: number;
  height: number;
  /** Seconds. */
  duration: number;
};

export const VIDEO_PRESETS: VideoPreset[] = [
  { id: "aurora", name: "Aurora", width: 1440, height: 1440, duration: 8 },
  { id: "sunset-flow", name: "Sunset Flow", width: 1440, height: 1440, duration: 8 },
];

export const getVideoPreset = (id: string) => VIDEO_PRESETS.find((p) => p.id === id);
let preferWebm: boolean | null = null;

/** The file the preview plays: the much smaller WebM where VP9 plays, else the MP4. */
export function videoPresetSrc(id: string): string {
  if (preferWebm === null && typeof document !== "undefined") {
    preferWebm = document.createElement("video").canPlayType('video/webm; codecs="vp9"') !== "";
  }
  return `/backgrounds/videos/${id}.${preferWebm === false ? "mp4" : "webm"}`;
}

/** Both encodings, preferred first (the exporter falls back if its decoder can't read one). */
export function videoPresetFiles(id: string): string[] {
  const preferred = videoPresetSrc(id);
  const other = preferred.endsWith(".webm") ? `/backgrounds/videos/${id}.mp4` : `/backgrounds/videos/${id}.webm`;
  return [preferred, other];
}
export const videoPresetThumbSrc = (id: string) => `/backgrounds/videos/${id}-thumb.jpg`;
